[2020-09-06-19:26:51]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F7D808>
[2020-09-06-19:32:38]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F7DF48>
[2020-09-06-19:43:59]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find'<traceback object at 0x111C7328>
[2020-09-06-20:01:37]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x138B9C28>
[2020-09-06-20:02:38]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x0127DE48>
[2020-09-06-20:03:38]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x012741A8>
[2020-09-06-20:04:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x11193FE8>
[2020-09-06-20:05:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x011D1828>
[2020-09-06-20:06:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x111933C8>
[2020-09-06-20:07:41]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x110DF608>
[2020-09-06-20:08:42]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x01275068>
[2020-09-06-20:09:43]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x138C3468>
[2020-09-06-20:10:44]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x10FA0D08>
[2020-09-06-20:11:45]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x1168E7A8>
[2020-09-06-20:42:04]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x11029EE8>
[2020-09-06-21:15:59]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x11129388>
[2020-09-06-21:22:33]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x02D96728>
[2020-09-06-22:37:42]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x138BF648>
[2020-09-06-22:50:02]from le360 : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x1131D8E8>
[2020-09-06-22:50:32]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F42228>
[2020-09-06-23:07:04]from le360 : <class 'AttributeError'>'NoneType' object has no attribute 'find'<traceback object at 0x011F55A8>
[2020-09-07-09:14:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571118>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:15:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74DE8>
[2020-09-07-09:16:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x115710E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:17:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x115712F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74C68>
[2020-09-07-09:18:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571598>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:19:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74A08>
[2020-09-07-09:20:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:55:09]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03E360E8>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x02BDBEC8>
[2020-09-07-10:04:35]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10EBE310>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x02B015E8>
[2020-09-07-12:53:35]from leseco : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='leseco.ma', port=443): Max retries exceeded with url: /resultats-saham-assurance-confirme-limpact-negatif-de-la-covid-19/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x014AE520>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x031F2248>
[2020-09-07-16:01:58]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11BD1688>
[2020-09-07-16:02:59]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11F38D28>
[2020-09-07-16:04:03]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x00F2AC68>
[2020-09-07-16:05:06]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11E73968>
[2020-09-07-16:06:09]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01822EA8>
[2020-09-07-16:07:11]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01877368>
[2020-09-07-16:08:13]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x11EE1148>
[2020-09-07-16:09:14]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01AA67C8>
[2020-09-07-16:10:18]from leseco : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='leseco.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x009AC048>
[2020-09-07-16:10:25]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x0EE9B528>
[2020-09-07-16:11:28]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01919688>
[2020-09-07-16:12:31]from afrique : <class 'ValueError'>not enough values to unpack (expected 3, got 2)<traceback object at 0x01917568>
[2020-09-07-16:15:21]from le360 : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x033CAA28>
[2020-09-07-17:37:37]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11520B68>
[2020-09-07-18:06:04]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x1372BF68>
[2020-09-07-18:24:17]from leseco : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='leseco.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x112EF6A8>
[2020-09-07-18:32:15]from hespress : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Read timed out. (read timeout=5)<traceback object at 0x116352E8>
[2020-09-08-09:32:02]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x136F22C8>
[2020-09-08-09:47:20]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00D038E8>
[2020-09-08-11:04:14]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x115518E8>
[2020-09-08-11:19:26]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00C594A8>
[2020-09-08-11:49:54]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11132B48>
[2020-09-08-12:05:10]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00FBEE08>
[2020-09-08-12:36:30]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11207BC8>
[2020-09-08-13:48:22]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00D435A8>
[2020-09-08-14:20:26]from le360 : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x123737A8>
[2020-09-08-16:50:38]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x112B27C8>
[2020-09-08-17:05:53]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x1106F6A8>
[2020-09-08-18:37:44]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x13704788>
[2020-09-08-21:56:16]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11385668>
[2020-09-08-22:57:14]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x114D5508>
[2020-09-09-02:00:09]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11035C08>
[2020-09-09-02:15:22]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x113C5288>
[2020-09-09-03:00:56]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11298DC8>
[2020-09-09-03:32:17]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x111A8EE8>
[2020-09-09-03:48:29]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x1155F8E8>
[2020-09-09-04:34:13]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11283928>
[2020-09-09-04:49:24]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00CE8948>
[2020-09-09-05:34:58]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x1131A3E8>
[2020-09-09-05:50:11]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x1102EC88>
[2020-09-09-06:35:46]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11385E08>
[2020-09-09-08:37:27]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11536628>
[2020-09-09-09:54:51]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11351888>
[2020-09-09-12:03:40]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00F92EE8>
[2020-09-09-15:20:37]from le360 : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x129C44A8>
[2020-09-09-15:52:57]from le360 : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x033D3288>
[2020-09-09-16:21:19]from hespress : <class 'AttributeError'>'NoneType' object has no attribute 'find'<traceback object at 0x137D61C8>
[2020-09-09-16:54:42]from hespress : <class 'requests.exceptions.ChunkedEncodingError'>("Connection broken: ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None)", ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))<traceback object at 0x13845CE8>
[2020-09-09-19:02:30]from afrique : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x0303F528>
[2020-09-09-22:00:32]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11464F88>
[2020-09-09-22:15:49]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11016F08>
[2020-09-09-22:31:06]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00D89108>
[2020-09-09-23:47:51]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x007CFA48>
[2020-09-10-00:03:04]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x110A1F48>
[2020-09-10-00:34:29]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x13741D08>
[2020-09-10-00:49:59]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x113C5108>
[2020-09-10-13:01:53]from leseco : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='leseco.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x0171EE68>
[2020-09-10-13:03:11]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00E88568>
[2020-09-10-13:03:12]from afrique : <class 'requests.exceptions.ReadTimeout'>HTTPConnectionPool(host='afrique.le360.ma', port=80): Read timed out. (read timeout=5)<traceback object at 0x121E0588>
[2020-09-10-15:02:27]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x1179EFA8>
[2020-09-10-15:02:29]from le360 : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x11741F08>
[2020-09-10-15:14:51]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x00B15888>
[2020-09-10-16:34:51]from le360 : <class 'django.db.utils.IntegrityError'>ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « article »
DETAIL:  La ligne en échec contient (79, t, f, f, f, t, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, null).
<traceback object at 0x117F3DE8>
[2020-09-10-16:40:59]from le360 : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x110465E8>
[2020-09-10-17:09:33]from le360 : <class 'django.db.utils.IntegrityError'>ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « article »
DETAIL:  La ligne en échec contient (80, t, f, f, f, t, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, null).
<traceback object at 0x0136FB08>
[2020-09-10-17:27:45]from hespress : <class 'django.db.utils.IntegrityError'>ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « article »
DETAIL:  La ligne en échec contient (81, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, t, f, f, f, f, f, f, f, f, f, f, null).
<traceback object at 0x1142B7A8>
[2020-09-10-18:03:14]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x0100BDE8>
[2020-09-10-18:27:41]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x0102EE88>
[2020-09-10-18:28:05]from hespress : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Read timed out. (read timeout=5)<traceback object at 0x00FBEE28>
[2020-09-10-18:30:05]from le360 : <class 'django.db.utils.IntegrityError'>ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « article »
DETAIL:  La ligne en échec contient (82, t, f, f, f, t, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, null).
<traceback object at 0x11ADF4E8>
[2020-09-10-19:13:33]from sport : <class 'requests.exceptions.ReadTimeout'>HTTPSConnectionPool(host='sport.le360.ma', port=443): Read timed out. (read timeout=5)<traceback object at 0x113FE928>
[2020-09-10-19:20:52]from hespress : <class 'django.db.utils.IntegrityError'>ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « article »
DETAIL:  La ligne en échec contient (83, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, t, f, f, f, f, f, f, f, f, f, f, null).
<traceback object at 0x010F63A8>
[2020-09-10-19:24:56]from hespress : <class 'django.db.utils.ProgrammingError'>ERREUR:  la colonne « article » de la relation « home_category » n'existe pas
LINE 1: ... "simp_comp", "title", "image", "source", "date", "article")...
                                                             ^
<traceback object at 0x1380F728>
[2020-09-10-19:25:57]from hespress : <class 'django.db.utils.ProgrammingError'>ERREUR:  la colonne « article » de la relation « home_category » n'existe pas
LINE 1: ... "simp_comp", "title", "image", "source", "date", "article")...
                                                             ^
<traceback object at 0x115E4148>
[2020-09-10-19:26:58]from hespress : <class 'django.db.utils.ProgrammingError'>ERREUR:  la colonne « article » de la relation « home_category » n'existe pas
LINE 1: ... "simp_comp", "title", "image", "source", "date", "article")...
                                                             ^
<traceback object at 0x01129488>
[2020-09-10-19:27:59]from hespress : <class 'django.db.utils.ProgrammingError'>ERREUR:  la colonne « article » de la relation « home_category » n'existe pas
LINE 1: ... "simp_comp", "title", "image", "source", "date", "article")...
                                                             ^
<traceback object at 0x0E719B28>
